name: Deploy to IONOS Webspace

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Check out the repository
            - name: Checkout Code
              uses: actions/checkout@v3

            # Step 2: Deploy files to IONOS webspace via SFTP
            - name: Deploy via SFTP
              uses: appleboy/scp-action@v0.1.2
              with:
                  host: ${{ secrets.SFTP_HOST }}
                  username: ${{ secrets.SFTP_USER }}
                  password: ${{ secrets.SFTP_PASS }}
                  port: 22
                  source: './'
                  target: '/blueAnt'
                  rm: true
