name: CD

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Check out the code
            - name: Checkout Code
              uses: actions/checkout@v3

            # Step 2: Install sshpass
            - name: Install sshpass
              run: sudo apt-get install -y sshpass

            # Step 3: Transfer the blueAnt directory to the server via SCP
            - name: Transfer files to server
              env:
                  SFTP_HOST: ${{ secrets.SFTP_HOST }}
                  SFTP_USER: ${{ secrets.SFTP_USER }}
                  SFTP_PASS: ${{ secrets.SFTP_PASS }}
              run: |
                  sshpass -p "$SFTP_PASS" scp -o StrictHostKeyChecking=no -r ./blueAnt $SFTP_USER@$SFTP_HOST:/blueAnt
